"""initial migration

Revision ID: 0af3b0f13311
Revises: 
Create Date: 2025-05-12 00:10:53.226913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af3b0f13311'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('firma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adi', sa.String(length=120), nullable=False),
    sa.Column('vkn', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vkn')
    )
    op.create_index(op.f('ix_firma_adi'), 'firma', ['adi'], unique=False)
    op.create_table('finansal_veri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('donem', sa.String(length=20), nullable=True),
    sa.Column('aktif_toplami', sa.Float(), nullable=True),
    sa.Column('kisa_vadeli_borclar', sa.Float(), nullable=True),
    sa.Column('dagitilmamis_karlar', sa.Float(), nullable=True),
    sa.Column('faiz_vergi_oncesi_kar', sa.Float(), nullable=True),
    sa.Column('oz_sermaye_piyasa_degeri', sa.Float(), nullable=True),
    sa.Column('toplam_borclar', sa.Float(), nullable=True),
    sa.Column('yillik_satislar', sa.Float(), nullable=True),
    sa.Column('altman_z_skoru', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finansal_veri')
    op.drop_index(op.f('ix_firma_adi'), table_name='firma')
    op.drop_table('firma')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
